### ISSUE TITLE
oem type not working on tumbleweed s390x

### ISSUE THREAD

**Issue by azouhr** [OSInside/kiwi#1296]
## Problem description
I just tried to reproduce the configuration found in build-tests/s390/suse/test-image-oem/. While creating the zipl config, the build breaks:

<pre>
[ INFO    ]: 18:03:30 | Creating zipl config file from template
[ ERROR   ]: 18:03:30 | Unexpected error:
Traceback (most recent call last):
  File "/usr/bin/kiwi-ng", line 11, in <module>
    load_entry_point('kiwi==9.18.31', 'console_scripts', 'kiwi-ng')()
  File "/usr/lib/python3.7/site-packages/kiwi/kiwi.py", line 66, in main
    App()
  File "/usr/lib/python3.7/site-packages/kiwi/app.py", line 35, in __init__
    task_class().process()
  File "/usr/lib/python3.7/site-packages/kiwi/tasks/system_build.py", line 276, in process
    result = image_builder.create()
  File "/usr/lib/python3.7/site-packages/kiwi/builder/disk.py", line 183, in create
    result = disk.create_disk()
  File "/usr/lib/python3.7/site-packages/kiwi/builder/disk.py", line 449, in create_disk
    self._install_bootloader(device_map)
  File "/usr/lib/python3.7/site-packages/kiwi/builder/disk.py", line 993, in _install_bootloader
    boot_options=custom_install_arguments
  File "/usr/lib/python3.7/site-packages/kiwi/bootloader/config/zipl.py", line 152, in setup_disk_image_config
    'boot_options': ' '.join([self.cmdline, boot_options]),
TypeError: sequence item 1: expected str instance, dict found
</pre>
I did some more investigation and found that boot_options is a dictionary with the following content:
<pre>
dict_items([('boot_device', '/dev/mapper/loop0p1'), ('root_device', '/dev/systemVG/LVRoot'), ('firmware', <kiwi.firmware.FirmWare object at 0x3ff8654ca58>), ('target_removable', None), ('system_volumes', {'home': {'volume_options': 'defaults', 'volume_device': '/dev/systemVG/home'}})])
</pre>
## Expected behaviour
A reasonable zipl config should be written.

## Steps to reproduce the behaviour
Use the test from this github project found at build-tests/s390/suse/test-image-oem

## OS and Software information
+ KIWI version:  python3-kiwi-9.18.31-1.1.s390x
+ Operating system: openSUSE Tumbleweed
+ OBS version: manual build with the command:
 kiwi-ng --type oem system build --description test-image-oem --target-dir /var/tmp/kiwi/test-image-oem

**Comment by schaefi** [comment]
Hi, the mentioned problem has been fixed in in #1264 

The updated kiwi version seems to not have made its way to tumbleweed. Please double check with our unit test build here:

https://build.opensuse.org/project/show/Virtualization:Appliances:Images:Testing_s390:suse

and re-open if the bug still exists.

Thanks
